ALTER TABLE `RoomType`
  ADD COLUMN `amenities` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  ADD COLUMN `photos` JSON NOT NULL DEFAULT (JSON_ARRAY());

ALTER TABLE `Room`
  ADD COLUMN `capacity` INTEGER NULL,
  ADD COLUMN `dailyPrice` DECIMAL(10, 2) NULL,
  ADD COLUMN `amenities` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  ADD COLUMN `photos` JSON NOT NULL DEFAULT (JSON_ARRAY());

ALTER TABLE `Room` MODIFY COLUMN `status` ENUM('AVAILABLE', 'RESERVED', 'OCCUPIED', 'CLEANING', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE';
